# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)

In [ ]:
print(A.shape)
print(A.size)
print(A.dtype)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

subtraction = B - C
addition = B + C
multi = B@C

print(B)
print(C)
print(addition)
print(subtraction)
print(multi)


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

In [ ]:
exp = np.exp(B)
print(exp)

min_value = np.min(B)
print(min_value)

max_value = np.max(B)
print(max_value)

min_value_column = np.min(B, 0)
print(min_value_column)

min_value_row = np.min(B, 1)
print(min_value_row)

min_values_index = np.argmin(B)
print(min_values_index)

min_values_row_index = np.argmin(B, 1)
print(min_values_row_index)

matrix_sum = B.sum()
print(matrix_sum)

matrix_mean = B.mean()
print(matrix_mean)

matrix_median = np.median(B)
print(matrix_median)

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
for i in A:
    for x in i:
        print(x)

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

In [ ]:
""" It creates a three dimensional array.
The first dimension has a size of two = two groups
The second dimension has the size of three 0 each group has three rows
The third dimension is calculated by numpy when defined as -1 = five elements in each row"""

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

print(m1.shape)
print(m2.shape)
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [11]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(isinstance(A, np.ndarray))
print(B)
print(C)
print(D)
print(E)

True
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [12]:
def add_mult_matrices(m1, m2, calc_method=''):
    if isinstance(m1, np.ndarray) and isinstance(m2, np.ndarray):
        if calc_method == 'add':
            if m1.shape == m2.shape:
                print('m1 + m2 =', m1+m2)
            else:
                raise ValueError('m1 and m2 does not have the same size')
        elif calc_method == 'multiply':
                if m1.shape[1] == m2.shape[0]:
                    print('m1 + m2 =', m1 @ m2)
                else:
                    raise ValueError('m1 and m2 does not have the right size for multiplication')
        else:
            raise ValueError('Choose either "add" or "multiply"')
    elif isinstance(m1, np.ndarray):
        raise ValueError("m1 is a NumPy array, but m2 is not")
    elif isinstance(m2, np.ndarray):
        raise ValueError("m2 is a NumPy array, but m1 is not")
    else:
        raise("Neither m1 nor m2 is a NumPy array")

W = add_mult_matrices(C, D, 'multiply')

m1 + m2 = [[11 10]
 [10 11]]


**Chap2. Question 2**

In [ ]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

def check_matrices(m1, m2, m3):
    if (m2!=m3).all():
        if (m1 @ m2 == m1 @ m3).all():
            print('AB and AC are equal, but B and C are NOT equal')
        else:
            print('AB and AC are NOT equal, and B and C are NOT equal')
    else:
        print('B and C are equal')
        
check = check_matrices(A, B, C)



**Chap2. Question 3**

In [ ]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

AD = A @ D
DA = D @ A
print(AD)
print(DA)

**Quiz p.11, Question 2**

In [ ]:
M1 = np.array([[1, -1], [-1, 1]])
M2 = np.array([[-1, 1], [1, -1]])

A = np.array([[-2, 2], [2, -2]])
B = np.array([[2, -2], [-2, 2]])
C = np.array([[-2, 2], [-2, 2]])
D = np.array([[-2, -2], [2, 2]])

def check_m1_m2(m1, m2):
    if (m1 @ m2 == A).all():
        print('M1 * M2 == A\n', 'A:\n', A)
    elif (m1 @ m2 == B).all():
        print('M1 * M2 == B')
    elif (m1 @ m2 == C).all():
        print('M1 * M2 == C')
    elif (m1 @ m2 == D).all():
        print('M1 * M2 == D')
    else:
        raise ValueError('M1 * M2 is not equal to any of the matrices')

print(check_m1_m2(M1, M2))

**Chap 6. Question 1**

In [2]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)

print("Inverse of A:")
print(A_inverse)

print("\nInverse of B:")
print(B_inverse)

Inverse of A:
[[ 5. -6.]
 [-4.  5.]]

Inverse of B:
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [4]:
A = np.array([[2, 2], [1, 2]])
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [6]:
array_a = np.array([[2, 2], [1, 2]])
array_b = np.array([[1, 0], [0, -1]])
array_c = np.array([[0, 1], [1, 0]])
array_d = np.array([[1, -1], [0, -0]])

array_list = [array_a, array_b, array_c, array_d]

for array in array_list:
    array_transpose = array.T
    is_orthogonal = np.allclose(np.dot(array_transpose, array), np.eye(array.shape[0]))
    
    if is_orthogonal:
        print(array, '\n Matrix is orthogonal')
    else:
        print(array, '\n Matrix is not orthogonal')

[[2 2]
 [1 2]] 
 Matrix is not orthogonal
[[ 1  0]
 [ 0 -1]] 
 Matrix is orthogonal
[[0 1]
 [1 0]] 
 Matrix is orthogonal
[[ 1 -1]
 [ 0  0]] 
 Matrix is not orthogonal


**Chap10. Question 1 b)**

In [ ]:
""" See above code, i did A-D in the same code """

**Chap 12. Question 1**

In [7]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [8]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [9]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [10]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
